### PR TITLE
Github pages + API reference

### PR DESCRIPTION
**Pull request by TheWolfNL**
Okay so this is no documentation, but it can help find what's available etc.
So take a look, and if you like it, that'd be great.

Things added in this PR:

- API Reference  (this will generate pages like https://thewolfnl.github.io/parable/docs )
- Using github pages (this will generate a page like https://thewolfnl.github.io/parable/ )

To generate the API reference just call `vendor/bin/apigen generate` and it will update the `docs/` directory.

### CODE REVIEW

**Comment by devvoh** [comment]
Haha, that's awesome, man! Thanks for the PR :)

I'll be looking into this sort of thing more once the 0.11.x branch is getting close to being finished. I'll leave this PR open and revisit it by then.

**Comment by TheWolfNL** [comment]
Yesterday I came across https://www.phpdoc.org/ (dóh) and that looked nice as well, but could also try to figure that one out.

**Comment by devvoh** [comment]
Yeah, I was looking into that one as well. There's multiple options, but I hadn't looked at ApiGen yet, so by the time I've nailed down the API I've got some comparing (and additional commenting) to do :D

**Comment by TheWolfNL** [comment]
Main reason I used apigen, is because I didn't read properly, thinking phpdocumentor needed PEAR and stuff, but I just noticed that using composer would be okay as well.

Do you want me to create a phpdocumentor branch for the 0.11.x?

**Comment by devvoh** [comment]
I can't stop you, but I will say that I'm rather picky about the kind of documentation I myself prefer to see, and it usually isn't an API reference :)

Think more like Laravel's docs, with examples and additional information. I've been working on it, actually, but with the API changing significantly in 0.11.x, I've taken a break until it solidifies a bit.

Just want to make sure you're not spending time on something I might not end up using :)

**Comment by TheWolfNL** [comment]
Fine by me 😛 Let me know If you do want to add the API reference

**Comment by devvoh** [comment]
Oh, you'll know :D

**Comment by devvoh** [comment]
Now that 0.11.0 is out, I'm closing this. The suggestions aren't forgotten, though, and will be taken into consideration when the documentation writing process starts. Don't think an API reference of some sort would hurt 🙂

**Pull request closed without merging**
